### ISSUE TITLE
User can create different grade components for a subject

### ISSUE THREAD

**Issue by max172-hqt** [max172-hqt/grade-tracker#2]
As a user, I can **create different grade components for a subject**

**Comment by jeffverz** [comment]
TODO:
- [x] edit initial grade components prior to saving the new course
- [x] add grade component prior to saving the new course
- [x] validation of inputs

**Comment by jeffverz** [comment]
The issue couldn't be completed because of technical difficulties encountered when saving the  new grade component names, weight, and max score, prior to completion of adding new courses. 

First, the logical implementation was inappropiate, but we are already managed to rectify it, and are now on the right track  to finishing it in the next sprint.

**Comment by max172-hqt** [comment]
Complete this.
